services:
  db:
    build: ./db/image
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django -d open_mes"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    build:
      context: ./backend/image
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             gunicorn base.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend/src:/open_mes
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/base/health/"]
      interval: 30s
      timeout: 10s
      retries: 5

  worker:
    container_name: worker
    build:
      context: ./backend/image
      dockerfile: Dockerfile
    command: celery -A base worker -l info
    volumes:
      - ./backend/src:/open_mes
    env_file:
      - .env
    depends_on:
      backend:
        condition: service_started
      redis:
        condition: service_healthy

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    depends_on:
      backend:
        condition: service_healthy

  reverse-proxy:
    container_name: reverse-proxy
    build: ./reverse-proxy
    ports:
      - "8100:80"
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
