services:
  postgres:
    container_name: postgres
    build: ./image
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "django"
      POSTGRES_PASSWORD: "django"
      POSTGRES_DB: "open_mes"
    
    networks:
      - open_mes

networks:
  open_mes:
    external: true