"""
Django settings for base project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

import os
import environ

VERSION = '0.0.0'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
# .env ファイルのパスを BASE_DIR (open_mes/scr/) から正しく指定します。
# これにより、manage.py がどのディレクトリから実行されても .env ファイルを確実に見つけられます。
dotenv_path = BASE_DIR / '.env'
env.read_env(str(dotenv_path))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')

DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK" : lambda request: env.bool('DEBUG'),
    "FETCH_INSTRUMENTATION_ENABLED": False,
}

if env.list('CSRF_TRUSTED_ORIGINS') != ['*']:
    CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',
    'django_static_md5url',
    'production.apps.ProductionConfig',
    'inventory.apps.InventoryConfig',
    'machine.apps.MachineConfig',
    'quality.apps.QualityConfig',
    'master.apps.MasterConfig',
    'mobile.apps.MobileConfig',
    'debug_toolbar',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'mobile.middleware.AutoMobileRedirectMiddleware', # Automatically redirect mobile users
    'django.contrib.messages.middleware.MessageMiddleware',
    'users.middleware.PasswordExpirationMiddleware', # パスワード有効期限
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'base.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates/'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'base.context_processors.my_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'base.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': env.db(),

}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_DIR = os.path.join(BASE_DIR, "static")
STATIC_URL = '/static/'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication', # 追加
        'rest_framework.authentication.TokenAuthentication',
    ]
}

if DEBUG == True:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, "static")
    ]

else:
    STATIC_ROOT = STATIC_DIR

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# カスタムユーザー
AUTH_USER_MODEL = 'users.CustomUser'
LOGIN_URL = 'users:login'  # ログインページのURL
LOGIN_REDIRECT_URL = 'main'  # ログイン後のリダイレクト先
LOGOUT_REDIRECT_URL = 'main'  # ログアウト後のリダイレクト先

# settings.py
# ... other settings

PASSWORD_EXPIRATION_DAYS = 180 # 例: 90日

# 有効期限を無効にする場合は 0 や None を設定
# PASSWORD_EXPIRATION_DAYS = None
